config/routes.rb
Rails.application.routes.draw do

  devise_for :users 
  resources :users, only: [:update]

  devise_scope :user do
    get 'login' => 'devise/sessions#new'
    post 'login' => 'devise/sessions#create'
  end

  resources :topics do 
    resources :entries 
    # except: [:index]
  end

  get 'about' => 'welcome#about'

  # get 'index' => 'entries#index'
  
  root to: 'welcome#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :entry
end

app/models/entry.rb
class Entry < ActiveRecord::Base
	has_many :comments
	belongs_to :user
	belongs_to :topic

	default_scope { order('created_at DESC') }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :entries
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :confirmable

  has_many :entries
  mount_uploader :avatar, AvatarUploader

  def admin?
  	role == 'admin'
  end

  def moderator?
  	role == 'moderator'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
  	redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
  	@entries = Entry.all
    
    authorize @entries
  end

  def show
  	@entry = Entry.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    authorize @entry
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @entry = Entry.new
    authorize @entry
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @entry = current_user.entries.build(params.require(:entry).permit(:title, :body))
    authorize @entry
    if @entry.save
      flash[:notice] = "Entry was saved."
      redirect_to [@topic, @entry]
    else
      flash[:error] = "There was an error creating your entry. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @entry = Entry.find(params[:id])
    authorize @entry
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @entry = Entry.find(params[:id])
    authorize @entry
    if @entry.update_attributes(params.require(:entry).permit(:title, :body))
      flash[:notice] = "Entry was updated"
      redirect_to [@topic, @entry]
    else
      flash[:error] = "There was an error saving your entry. Please try again."
      render :edit
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
  	@topics = Topic.all
  	authorize @topics
  end

  def new
  	@topic = Topic.new
  	authorize @topic
  end

  def show
  	@topic = Topic.find(params[:id])
    @entries = @topic.entries
  	authorize @topic
  end

  def edit
  	@topic = Topic.find(params[:id])
  	authorize @topic
  end

  def create
  	@topic = Topic.new(params.require(:topic).permit(:name, :description, :public))
  	authorize @topic
  	if @topic.save
  		redirect_to @topic
  	else
  		flash[:error] = "Error creating topic."
  		render :new
  	end
  end

  def update
  	@topic = Topic.find(params[:id])
  	authorize @topic
  	if @topic.update_attributes(params.require(:topic).permit(:name, :description, :public))
  		redirect_to @topic
  	else
  		flash[:error] = "Error saving topic."
  		render :edit
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!
 
   def update
     if current_user.update_attributes(user_params)
       flash[:notice] = "User information updated"
       redirect_to edit_user_registration_path
     else
       flash[:error] = "Invalid user information"
       redirect_to edit_user_registration_path
     end
   end
 
   private
 
   def user_params
     params.require(:user).permit(:name, :avatar)
   end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#allow login anywhere in the app
	def resource_name
    :user
  end

	def resource
  	@resource ||= User.new
	end

	def devise_mapping
  	@devise_mapping ||= Devise.mappings[:user]
	end

  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
    else
      content_tag :div, capture(&block), class: 'form-group'
    end
  end

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/_form.html.erb
<%= form_for [topic, entry] do |f| %>
   <% if entry.errors.any? %>
     <div class="alert alert-danger">
       <h4>There are <%= pluralize(entry.errors.count, "error") %>.</h4>
       <ul>
         <% entry.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
   <%= form_group_tag(entry.errors[:title]) do %>
     <%= f.label :title %>
     <%= f.text_field :title, class: 'form-control', placeholder: "Enter title" %>
   <% end %>
   <%= form_group_tag(entry.errors[:body]) do %>
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter body" %>
   <% end %>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/entries/edit.html.erb
<h1>Edit Entry</h1>

<%= render partial: 'form', locals: { topic: @topic, entry: @entry } %>

app/views/entries/index.html.erb
<h1>All Entries</h1>
<% if policy(Entry.new).create? %>
  <%= link_to "New Entry", new_topic_entry_path, class: 'btn btn-success' %>
<% end %>

<% @entries.each do |entry| %>
	<div class="media">
		<div class="media-body">
			<h4 class="media-heading">
				<%= link_to entry.title, entry %>
			</h4>
			<small>
			submitted <%= time_ago_in_words(entry.created_at) %> ago by
			<%= entry.user.name %> <br>
			<%= entry.comments.count %> Comments
			</small>
		</div>
	</div>
<% end %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render partial: 'form', locals: { topic: @topic, entry: @entry } %>

app/views/entries/show.html.erb
<h1><%= markdown_to_html @entry.title %></h1>

<p><%= markdown_to_html @entry.body %></p>

<small>
 <%= image_tag(@entry.user.avatar.tiny.url) if @entry.user.avatar? %>
 submitted <%= time_ago_in_words(@entry.created_at) %> ago by
 <%= @entry.user.name %>
</small>

<% if policy(@entry).edit? %>
  <%= link_to "Edit", edit_topic_entry_path(@topic,@entry), class: 'btn btn-success' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WellesleyUrbanDictionary</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<ul class="nav nav-tabs">
			<li role="presentation"><%= link_to "Home", root_path %></li>
			<li role="presentation"><%= link_to "About", about_path %></li>
			<li role="presentation"><%= link_to "All Topics", topics_path %></li>

			<div class="pull-right user-info">
				<% if current_user %>
				<%= image_tag(current_user.avatar.tiny.url) if current_user.avatar? %>
					Hello
					<%= link_to (current_user.name || current_user.email), edit_user_registration_path %>!
					<%= link_to "Sign out", destroy_user_session_path, method: :delete %>

				<% else %>
					<!-- <li class="dropdown"> -->
						<!-- remove sign in experiment -->
					<%= link_to "Sign In", new_user_session_path %>			
				<% end %>
			</div>
		</ul>

		<% if flash[:notice] %>
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash[:notice] %>
			</div>
		<% elsif flash[:error] %>
			<div class="alert alert-danger">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
			</div>
		<% elsif flash[:alert] %>
			<div class="alert alert-warning">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
			</div>
		<% end %>

		<section class="content">

			<%= yield %>

		</section>
	</div>

	<footer class="footer">
		<div class="container">
			<p class="text-muted">Brought to you by Polina Soshnin.</p>
		</div>
	</footer>
</body>
</html>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<%= form_for @topic do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control', placeholder: "Enter Topic Name" %>
	</div>

	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
	</div>
	
	<div class="form-group">
		<%= f.label :public, class: 'checkbox' do %>
			<%= f.check_box :public %> Public topic
		<% end %>
	</div>
	<%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/topics/index.html.erb
<h1>Topics</h1>

<% if policy(Topic.new).create? %>
	<%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
<% end %>

<% @topics.each do |topic| %>
  <div class="media">
  	<div class="media-body">
  	  <h4 class="media-heading">
  	  	<%= link_to topic.name, topic %>
  	  </h4>
      <small>
  	  	<%= topic.description %>
  	  </small>
  	</div>
  </div>
<% end %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= form_for @topic do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control', placeholder: "Enter Topic Name" %>
	</div>

	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
	</div>

	<div class="form-group">
		<%= f.label :public, class: 'checkbox' do %>
			<%= f.check_box :public %> Public topic
		<% end %>
	</div>
	<%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<% if policy(@topic).update? %>
	<%= link_to "Edit topic", edit_topic_path, class: 'btn btn-success' %>
<% end %>

<p class="lead"><%= @topic.description %></p>

<% @entries.each do |entry| %>
	<div class="media">
		<div class="media-body">
			<h4 class="media-heading">
				<%= link_to (markdown_to_html entry.title), [@topic, entry] %>
			</h4>
			<small>
				submitted <%= time_ago_in_words(entry.created_at) %> ago by
				<%= entry.user.name %> <br>
				<%= entry.comments.count %> Comments
			</small>

			<small>
				<%= image_tag(entry.user.avatar.tiny.url) if entry.user.avatar? %>
				submitted <%= time_ago_in_words(entry.created_at) %> ago by
				<%= entry.user.name %><br>
				<%= entry.comments.count %> Comments
	    </small>
		</div>
	</div>
<% end %>

<% if policy(Entry.new).create? %>
	<%= link_to "New Entry", new_topic_entry_path(@topic), class: 'btn btn-success' %>
<% end %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>